# Generated by Django 5.0.7 on 2024-07-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_checkout_status'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout',
        ),
        migrations.AddField(
            model_name='order',
            name='checkouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='cart.checkout'),
        ),
    ]
