# Generated by Django 5.0.7 on 2024-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_checkout_status'),
        ('order', '0003_alter_order_checkouts_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkouts',
        ),
        migrations.AddField(
            model_name='order',
            name='checkoutitems',
            field=models.ManyToManyField(related_name='orders', to='cart.checkoutitem'),
        ),
    ]
